media:
  input: public/media
  output: /media

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    filename: '{year}-{month}-{day}-{primary}.md'
    view:
      fields: [title, published, date]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: body
        label: Content
        type: rich-text
        required: true
  - name: config
    label: Jekyll config
    type: file
    path: _config.yml
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
      - name: url
        label: Website URL
        type: string
      - name: baseurl
        label: Base URL (for GitHub Pages repo sites)
        type: string

